dist: trusty
language: rust
rust:
  - stable
  - nightly
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - libdbus-1-dev
      - libgoogle-perftools-dev
      - libnotmuch-dev
      - pandoc
cache: cargo
os:
  - linux
matrix:
  allow_failures:
    - rust: nightly
env:
  - RUSTFLAGS="-D warnings"
script:
  - man/generate.sh man/test.1 && diff man/test.1 man/i3status-rs.1
  - rustup component add rustfmt
  - cargo fmt -- --check
  - cargo build --all-features --all-targets --verbose
  - cargo test --all-features --all-targets --verbose
